<div id="footer">
	<div id="productInfo">
		<a href="http://code.google.com/p/myschedule">${ myscheduleVersion }</a> - A Quartz Dashboard by 
		<a href="mailto:saltnlight5@gmail.com">Zemian Deng</a>
	</div>
	<div id="poweredBy">
		Powered by: 
		<a href="http://www.oracle.com/java">Java</a> 
		<a href="http://www.quartz-shecheduler.org">Quartz</a> 
		<a href="http://www.springframework.org">Spring</a>
		<a href="http://groovy.codehaus.org">Groovy</a>
		<a href="http://www.jquery.org">jQuery/UI</a>
		<a href="http://www.datatables.net">jQuery.DataTables</a>
	</div>
</div><!-- div.footer -->
