</div> <!-- div.container -->

<div class="footer">
<p class="productInfo">MySchedule - A Quartz Dashboard by <a href="mailto:saltnlight5@gmail.com">Zemian Deng</a></p>
<p class="poweredBy">Powered by: 
<a href="http://www.oracle.com/java">Java</a> 
<a href="http://www.quartz-shecheduler.org">Quartz</a> 
<a href="http://www.springframework.org">Spring</a>
<a href="http://groovy.codehaus.org">Groovy</a>
</p>
</div>

</body>
</html>