<div id="submenu">
<ul>
<li><a href="${ mainPath }/job/list">Jobs with trigger</a></li>
<li><a href="${ mainPath }/job/list-no-trigger-jobs">Jobs without trigger</a></li>
<li><a href="${ mainPath }/job/list-calendars">Calendars</a></li>
<li><a href="${ mainPath }/job/list-executing-jobs">Currently Executing Jobs</a></li>
<li><a href="${ mainPath }/job/load-xml">Load Jobs (Xml)</a></li>
<li><a href="${ mainPath }/job/job-history">Job History</a></li>
<li><a href="${ mainPath }/job/cron-tool">Cron Tool</a></li>
</ul>
</div>