package myschedule.service;

public enum ErrorCode {
	WEB_UI_PROBLEM,
	DATA_ACCESS_PROBLME,
	SERVICE_PROBLEM,
	SCRIPTING_PROBLEM,
	SCHEDULER_SERIVCE_NOT_FOUND,
	SCHEDULER_PROBLEM,
	GENERAL_PROBLEM;
}
